# Generated by Django 5.1.6 on 2025-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
