# Generated by Django 5.1.6 on 2025-03-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_historialmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nacimiento',
            field=models.DateField(blank=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
