# Generated by Django 5.1.6 on 2025-03-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_doctor_apellido_doctor_correo_doctor_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='clinicas.consulta'),
        ),
    ]
